public enum States
{
	TITLE_PAGE, 
	INSTRUCTIONS_PAGE, 
	LEVEL_SELECTION, 
	MAIN_GAME_EASY,
	MAIN_GAME_MEDIUM,
	MAIN_GAME_HARD, 
	TRANSITION_PAGE, 
	GAME_COMPLETION, 
	EXIT,
	OTHER // used for level selection
}